services:
  bridge:
    build: ./bridge
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  influxdb:
    image: influxdb:alpine
    ports:
      - '8086:8086/tcp'
    volumes:
      - influx-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: always

  mosquitto:
    build: ./mosquitto
    restart: always
    ports:
      - '1883:1883/tcp'

volumes:
  influx-data:
